{{- if .Values.spamassassin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mail-platform.fullname" . }}-spamassassin
  labels:
    {{- include "mail-platform.spamassassin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.spamassassin.replicaCount }}
  selector:
    matchLabels:
      {{- include "mail-platform.spamassassin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mail-platform.spamassassin.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: spamassassin
        image: "{{ .Values.spamassassin.image.repository }}:{{ .Values.spamassassin.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - name: spamd
          containerPort: 783
          protocol: TCP
        env:
        - name: REQUIRED_SCORE
          value: {{ .Values.spamassassin.config.required_score | quote }}
        - name: USE_BAYES
          value: {{ .Values.spamassassin.config.use_bayes | quote }}
        - name: BAYES_AUTO_LEARN
          value: {{ .Values.spamassassin.config.bayes_auto_learn | quote }}
        volumeMounts:
        - name: spamassassin-data
          mountPath: /var/lib/spamassassin
        resources:
          {{- toYaml .Values.spamassassin.resources | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: spamd
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: spamd
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: spamassassin-data
        emptyDir: {}
{{- end }}
