{{- if .Values.ldap.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mail-platform.fullname" . }}-ldap-secret
  labels:
    {{- include "mail-platform.ldap.labels" . | nindent 4 }}
type: Opaque
data:
  # LDAP admin password (base64 encoded)
  # Default: "changeme" - CHANGE THIS IN PRODUCTION!
  admin-password: {{ .Values.ldap.config.adminPassword | b64enc | quote }}
  
  # LDAP config password (base64 encoded)
  # Default: "changeme" - CHANGE THIS IN PRODUCTION!
  config-password: Y2hhbmdlbWU=
{{- end }}
