{{- if .Values.postfix.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mail-platform.fullname" . }}-postfix-secret
  labels:
    {{- include "mail-platform.postfix.labels" . | nindent 4 }}
type: Opaque
data:
  # TLS certificate and key (base64 encoded)
  # Replace these with your actual certificates
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYVENDQWtXZ0F3SUJBZ0lKQUk1N3JOWUpIOEg3TUEwR0NTcUdTSWIzRFFFQkN3VUFNRVl4Q3pBSkJnTlYKQkFZVEFsVlRNUXN3Q1FZRFZRUUlEQUpPV1RFUE1BMEdBMVVFQnd3R1RtVjNJRWx1Wmprd0N3WURWUVFLREFSTgplU0J0WVdsc0lITmxjblpsY2pBZUZ3MHlOREF4TURFd01EQXdNREJhRncweU5UQXhNREV3TURBd01EQmFNRVl4CkN6QUpCZ05WQkFZVEFsVlRNUXN3Q1FZRFZRUUlEQUpPV1RFUE1BMEdBMVVFQnd3R1RtVjNJRWx1Wmprd0N3WUQKVlFRS0RBUk5lU0J0WVdsc0lITmxjblpsY2pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQwpnZ0VCQU1BdFRxOHFIMXdwUUpsbVdQTmVWdWxsY3FzYjQxckgzcDk3dVB3OUJCVWRDZ1J6ckRydXF5bUtQb3J4CklmNkNJREJ1RkpJb2FVKzlyOURMS01JWmlIZlBJYjIwTXVwN2V0MU5mZUV0ejBXSFZ0N1IwS1hta0lKdW1oVFQKMUNZNzIyOTBScC9DdGUyT2xmQ2NGNUMzSk1XaXlneU9HeUxadnZYQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRREFMVTZ2S2g5Y0tVQ1oKWmxqelhsYnBaWEtyRytOYXg5NmZlN2o4UFFlRkF3b0VjNnc2N3FzcGlqNks4U0grZ2lBd2JoU1NLR2xQdmEvUQp5eWpDR1loM3p5Rzl0RExxZTNyZFRYM2hMYzlGaHNiZTBkQ2w1cENDYnBvVTA5UW1POXR2ZEVhZndyWHRqcFh3Cm5CZVF0eVRGb3NvTWpoc2kyYjcxd0E9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  
  # SASL passwords for SMTP authentication (if needed)
  sasl_passwd: ""
{{- end }}
