{{- if .Values.spamassassin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mail-platform.fullname" . }}-spamassassin
  labels:
    {{- include "mail-platform.spamassassin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.spamassassin.service.type }}
  ports:
  - port: {{ .Values.spamassassin.service.port }}
    targetPort: spamd
    protocol: TCP
    name: spamd
  selector:
    {{- include "mail-platform.spamassassin.selectorLabels" . | nindent 4 }}
{{- end }}
